
name: Deploy DEV

on:
  push:
    branches: [staging]

jobs:

  build:
    runs-on: ubuntu-latest

    name: 'Auto deploy'

    steps:
    - uses: appleboy/ssh-action@v0.1.4
      name: Connect to server
      with: 
        host: ${{ secrets.SERVER_HOST_DEV }}
        username: root
        key: ${{ secrets.SERVER_KEY_DEV}}
        port: 22
        script: |
          cd /var/www/ndp/staging
          git pull origin staging
